version: "3.9"

services:
  postgres:
    image: postgres:15.4
    container_name: postgres_prevt
    restart: always
    environment:
      POSTGRES_USER: prevt
      POSTGRES_PASSWORD: prevt
      POSTGRES_DB: prevt
    ports:
      - "5433:5432"              # accesso da host (facoltativo)
    volumes:
      - postgres_prevt:/var/lib/postgresql/data
    networks:
      - prevt_net

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.local
    container_name: spring_prevt
    restart: always
    volumes:
      - ./backend:/app          # üî• HOTSWAP codice
      - ~/.m2:/root/.m2          # üöÄ cache Maven
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: prevt
      DB_USER: prevt
      DB_PASSWORD: prevt

    depends_on:
      - postgres
    ports:
      - "8081:8080"
      - "5005:5005"              # üêû debug remoto
    networks:
      - prevt_net

  frontend:
    image: node:20-alpine
    container_name: prevt-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - prevt_net

volumes:
  postgres_prevt:

networks:
  prevt_net:
    driver: bridge
